AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Study CloudFormation

Resources:
  # ----------------------------
  # VPC
  # ----------------------------
  StudyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: aws-study-vpc

  # ----------------------------
  # Public Subnets
  # ----------------------------
  PublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref StudyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-northeast-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: aws-study-public-1a

  PublicSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref StudyVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: ap-northeast-1c
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: aws-study-public-1c

  # ----------------------------
  # Private Subnets
  # ----------------------------
  PrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref StudyVPC
      CidrBlock: 10.0.11.0/24
      AvailabilityZone: ap-northeast-1a
      Tags:
        - Key: Name
          Value: aws-study-private-1a

  PrivateSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref StudyVPC
      CidrBlock: 10.0.12.0/24
      AvailabilityZone: ap-northeast-1c
      Tags:
        - Key: Name
          Value: aws-study-private-1c

  # ----------------------------
  # Internet Gateway
  # ----------------------------
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: aws-study-igw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref StudyVPC
      InternetGatewayId: !Ref InternetGateway

  # ----------------------------
  # Public Route Table
  # ----------------------------
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref StudyVPC
      Tags:
        - Key: Name
          Value: aws-study-public-rt

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1aRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1a
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet1cRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1c
      RouteTableId: !Ref PublicRouteTable

  # ----------------------------
  # S3 VPC Endpoint 
  # ----------------------------
  S3VpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref StudyVPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref PublicRouteTable

  # ----------------------------
  # Security Group for EC2
  # ----------------------------
  StudyEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: aws-study-ec2-sg
      GroupDescription: Security group for aws-study-ec2
      VpcId: !Ref StudyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: aws-study-ec2-sg

  # ----------------------------
  # EC2 Instance
  # ----------------------------
  StudyEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}"
      KeyName: kentouwajima
      SubnetId: !Ref PublicSubnet1a
      SecurityGroupIds:
        - !Ref StudyEC2SecurityGroup
      Tags:
        - Key: Name
          Value: aws-study-ec2

  # ----------------------------
  # Security Group for RDS
  # ----------------------------
  StudyRDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: aws-study-rds-sg
      GroupDescription: Security group for aws-study-rds
      VpcId: !Ref StudyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref StudyEC2SecurityGroup
      Tags:
        - Key: Name
          Value: aws-study-rds-sg
  
  # ----------------------------
  # RDS Instance
  # ----------------------------
  StudyRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: aws-study-rds
      Engine: mysql
      EngineVersion: "8.0.43"
      DBName: awsstudy
      MasterUsername: root
      MasterUserPassword: rootroot
      DBInstanceClass: db.t4g.micro
      AllocatedStorage: 20
      MaxAllocatedStorage: 1000
      StorageType: gp2
      StorageEncrypted: false
      MultiAZ: false
      PubliclyAccessible: false
      Port: 3306
      VPCSecurityGroups:
        - !Ref StudyRDSSecurityGroup
      DBSubnetGroupName: !Ref StudyRDSSubnetGroup
      BackupRetentionPeriod: 7
      AutoMinorVersionUpgrade: true
      DeletionProtection: false
      EnableIAMDatabaseAuthentication: false
      Tags:
        - Key: Name
          Value: aws-study-rds

  # ----------------------------
  # RDS Subnet Group
  # ----------------------------
  StudyRDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: subnet group for aws-study-rds
      SubnetIds:
        - !Ref PrivateSubnet1a
        - !Ref PrivateSubnet1c

  # ----------------------------
  # Application Load Balancer
  # ----------------------------
  StudyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: aws-study-alb
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      Subnets:
        - !Ref PublicSubnet1a
        - !Ref PublicSubnet1c
      SecurityGroups:
        - !Ref StudyEC2SecurityGroup
      Tags:
        - Key: Name
          Value: aws-study-alb

  # ----------------------------
  # Target Group for ALB
  # ----------------------------
  StudyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: aws-study-tg
      TargetType: instance
      VpcId: !Ref StudyVPC
      Protocol: HTTP
      Port: 8080
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200
      Tags:
        - Key: Name
          Value: aws-study-tg
          
  # ----------------------------
  # ALB Listener
  # ----------------------------
  StudyALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref StudyALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref StudyTargetGroup
